CREATE TABLE IF NOT EXIST SFO_STATS.SRC__PASSENGER_STATISTICS (
	ACTIVITY_PERIOD VARCHAR(256),
	OP_AIRLINES VARCHAR(256),
	OP_CODE VARCHAR(256),
	PUB_AIRLINES VARCHAR(256),
	PUB_CODE VARCHAR(256),
	GEO_SUMM VARCHAR(256),
	GEO_REGION VARCHAR(256),
	ACTIVITY_TYPE VARCHAR(256),
	PRICE VARCHAR(256),
	TERMINAL VARCHAR(256),
	BOARDING_AREA VARCHAR(256),
	PAX_COUNT VARCHAR(256)
);

CREATE TABLE IF NOT EXIST SFO_STATS.SRC__CARGO_STATISTICS(
	ACTIVITY_PERIOD VARCHAR(256),
	OP_AIRLINES VARCHAR(256),
	OP_CODE VARCHAR(256),
	PUB_AIRLINES VARCHAR(256),
	PUB_CODE VARCHAR(256),
	GEO_SUMM VARCHAR(256),
	GEO_REGION VARCHAR(256),
	ACTIVITY_TYPE VARCHAR(256),
	CARGO_TYPE VARCHAR(256),
	CARGO_AIRCRAFT_TYPE VARCHAR(256),
	CARGO_WEIGHT_LBS VARCHAR(256),
	CARGO_WEIGHT_TONS VARCHAR(256)
);

CREATE TABLE IF NOT EXIST SFO_STATS.SRC__LANDING_STATISTICS(
	ACTIVITY_PERIOD VARCHAR(256),
	OP_AIRLINES VARCHAR(256),
	OP_CODE VARCHAR(256),
	PUB_AIRLINES VARCHAR(256),
	PUB_CODE VARCHAR(256),
	GEO_SUMM VARCHAR(256),
	GEO_REGION VARCHAR(256),
	ACTIVITY_TYPE VARCHAR(256),
	LANDING_AIRCRAFT_TYPE VARCHAR(256),
	AIRCRAFT_MANU VARCHAR(256),
	AIRCRAFT_MODEL VARCHAR(256),
	AIRCRAFT_VERSION VARCHAR(256),
	LANDING_COUNT VARCHAR(256),
	TOTAL_LANDED_WEIGHT VARCHAR(256)
);