-- Transform pax stats data
INSERT INTO STG__SFO_STATS.UNIQUE__PASSENGER_STATISTICS (
	ACTIVITY_PERIOD,
	OP_AIRLINES,
	OP_CODE,
	PUB_AIRLINES,
	PUB_CODE,
	GEO_SUMM,
	GEO_REGION,
	ACTIVITY_TYPE,
	PRICE,
	TERMINAL,
	BOARDING_AREA,
	PAX_COUNT
) SELECT DISTINCT
	ACTIVITY_PERIOD,
	OP_AIRLINES,
	OP_CODE,
	PUB_AIRLINES,
	PUB_CODE,
	GEO_SUMM,
	GEO_REGION,
	ACTIVITY_TYPE,
	PRICE,
	TERMINAL,
	BOARDING_AREA,
	PAX_COUNT
FROM SRC__SFO_STATS.SRC__CLEAN__PASSENGER_STATISTICS 
;


-- Transform cargo stats data
INSERT INTO STG__SFO_STATS.UNIQUE__CARGO_STATISTICS(
	ACTIVITY_PERIOD,
	OP_AIRLINES,
	OP_CODE,
	PUB_AIRLINES,
	PUB_CODE,
	GEO_SUMM,
	GEO_REGION,
	ACTIVITY_TYPE,
	CARGO_TYPE,
	CARGO_AIRCRAFT_TYPE,
	CARGO_WEIGHT_LBS,
	CARGO_WEIGHT_TONS
) SELECT DISTINCT
	ACTIVITY_PERIOD,
	OP_AIRLINES,
	OP_CODE,
	PUB_AIRLINES,
	PUB_CODE,
	GEO_SUMM,
	GEO_REGION,
	ACTIVITY_TYPE,
	CARGO_TYPE,
	CARGO_AIRCRAFT_TYPE,
	CARGO_WEIGHT_LBS,
	CARGO_WEIGHT_TONS
FROM SRC__SFO_STATS.SRC__CLEAN__CARGO_STATISTICS
;

-- Transform landing data
INSERT INTO STG__SFO_STATS.UNIQUE__LANDING_STATISTICS(
	ACTIVITY_PERIOD,
	OP_AIRLINES,
	OP_CODE,
	PUB_AIRLINES,
	PUB_CODE,
	GEO_SUMM,
	GEO_REGION,
	LANDING_AIRCRAFT_TYPE,
	BODY_TYPE,
	AIRCRAFT_MANU,
	AIRCRAFT_MODEL,
	AIRCRAFT_VERSION,
	LANDING_COUNT,
	TOTAL_LANDED_WEIGHT
) SELECT DISTINCT
	ACTIVITY_PERIOD,
	OP_AIRLINES,
	OP_CODE,
	PUB_AIRLINES,
	PUB_CODE,
	GEO_SUMM,
	GEO_REGION,
	LANDING_AIRCRAFT_TYPE,
	BODY_TYPE,
	AIRCRAFT_MANU,
	AIRCRAFT_MODEL,
	AIRCRAFT_VERSION,
	LANDING_COUNT,
	TOTAL_LANDED_WEIGHT
FROM SRC__SFO_STATS.SRC__CLEAN__LANDING_STATISTICS
;
