version: '3.7'

services:
  gooddata-cn-ce:
    image: gooddata/gooddata-cn-ce:latest
    container_name: gooddata-cn
    ports:
      - "3000:3000"
      - "5432:5432"
    volumes:
      - gooddata-cn-ce-data:/data2
    environment:
      LICENSE_AND_PRIVACY_POLICY_ACCEPTED: "YES"
      BUNDLE_TYPE: "gdc"
      APP_LOGLEVEL: "INFO"

  sfodb-postgres:
    image: postgres:14.2
    container_name: sfodb-postgres
    environment:
      - POSTGRES_USER=sfo
      - POSTGRES_PASSWORD=sfo
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '8731:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  gooddata-cn-ce-data:
  local-postgres: