TRUNCATE TABLE OUT__SFO_STATS.OUT__AIRLINE CASCADE;

INSERT INTO OUT__SFO_STATS.OUT__AIRLINE(
	ITAT_CODE,
	AIRLINE_NAME
) SELECT
	PUB_CODE,
	PUB_AIRLINES
FROM STG__SFO_STATS.UNIQUE__PASSENGER_STATISTICS
UNION
SELECT
	PUB_CODE,
	PUB_AIRLINES
FROM STG__SFO_STATS.UNIQUE__CARGO_STATISTICS
UNION
SELECT
	PUB_CODE,
	PUB_AIRLINES
FROM STG__SFO_STATS.UNIQUE__LANDING_STATISTICS
;