TRUNCATE TABLE OUT__SFO_STATS.OUT__ACTIVITY CASCADE;


INSERT INTO OUT__SFO_STATS.OUT__ACTIVITY(
	ACTIVITY_TYPE
) SELECT DISTINCT
	ACTIVITY_TYPE
FROM STG__SFO_STATS.UNIQUE__PASSENGER_STATISTICS
UNION
SELECT DISTINCT
	ACTIVITY_TYPE
FROM STG__SFO_STATS.UNIQUE__CARGO_STATISTICS
UNION
SELECT DISTINCT
	ACTIVITY_TYPE
FROM STG__SFO_STATS.UNIQUE__CARGO_STATISTICS
;