TRUNCATE TABLE OUT__SFO_STATS.OUT__PASSENGER_FLIGHTS_STATISTICS CASCADE;

INSERT INTO OUT__SFO_STATS.OUT__PASSENGER_FLIGHTS_STATISTICS(
	TERMINAL,
	BOARDING_AREA,
	PASSENGER_COUNT,
	ACTIVITY_TYPE,
	AIRLINE_RECORD_ID,
	LOCATION_ID,
	PRICE_CATEGORY,
	FLIGHT_DATE
) SELECT
	L.TERMINAL,
	L.BOARDING_AREA,
	L.PAX_COUNT,
	L.ACTIVITY_TYPE,
	M.AIRLINE_RECORD_ID,
	R.LOCATION_ID,
	L.PRICE,
	L.ACTIVITY_PERIOD
FROM STG__SFO_STATS.UNIQUE__PASSENGER_STATISTICS AS L
JOIN OUT__SFO_STATS.OUT__AIRLINE AS M
ON L.PUB_CODE = M.ITAT_CODE AND L.PUB_AIRLINES = M.AIRLINE_NAME
JOIN OUT__SFO_STATS.OUT__DESTINATION_ORIGIN AS R
ON L.GEO_SUMM = R.GEO_SUMM AND L.GEO_REGION = R.GEO_REGION
;