TRUNCATE TABLE OUT__SFO_STATS.OUT__LANDING_STATISTICS CASCADE;

INSERT INTO OUT__SFO_STATS.OUT__LANDING_STATISTICS(
	AIRCRAFT_BODY_TYPE,
	AIRCRAFT_MANUFACTURER,
	AIRCRAFT_MODEL,
	LANDING_AIRCRAFT_TYPE,
	LANDING_WEIGHT,
	LANDING_COUNT,
	AIRLINE_RECORD_ID,
	LOCATION_ID,
	FLIGHT_DATE
) SELECT
	L.BODY_TYPE,
	L.AIRCRAFT_MANU,
	CONCAT(L.AIRCRAFT_MODEL,'-',L.AIRCRAFT_VERSION),
	L.LANDING_AIRCRAFT_TYPE,
	L.TOTAL_LANDED_WEIGHT,
	L.LANDING_COUNT,
	M.AIRLINE_RECORD_ID,
	R.LOCATION_ID,
	L.ACTIVITY_PERIOD
FROM STG__SFO_STATS.UNIQUE__LANDING_STATISTICS AS L
JOIN OUT__SFO_STATS.OUT__AIRLINE AS M
ON L.PUB_CODE = M.ITAT_CODE AND L.PUB_AIRLINES = M.AIRLINE_NAME
JOIN OUT__SFO_STATS.OUT__DESTINATION_ORIGIN AS R
ON L.GEO_SUMM = R.GEO_SUMM AND L.GEO_REGION = R.GEO_REGION
;